stages:
  - build

pages:
  stage: build
  image: node:latest
  script:
    - npm i
    - mkdir public/
    - npm run resume export -- --theme elegant public/index.html
  artifacts:
    paths:
      - public